export type CatalogEntry = {
  id: string;
  role: "official" | "parallel" | "manual";
  nameEn: string;
  nameAr: string;
  summaryEn: string;
  summaryAr: string;
  licence: string;
  licenceUrl: string;
  sourceUrl: string;
};

export const PROVIDER_CATALOG: CatalogEntry[] = [
  {
    id: "hmrc",
    role: "official",
    nameEn: "HMRC monthly exchange rates",
    nameAr: "أسعار الصرف الشهرية لهيئة الإيرادات والجمارك البريطانية",
    summaryEn:
      "Primary official-reference series. UK customs rates published as foreign-currency units per 1 GBP and converted, inside this app, to dinars per one unit.",
    summaryAr:
      "السلسلة المرجعية الرسمية الأساسية. أسعار جمركية بريطانية منشورة كوحدات عملة أجنبية مقابل جنيه إسترليني واحد، ويحوّلها هذا التطبيق إلى دنانير مقابل وحدة واحدة.",
    licence: "Open Government Licence v3.0",
    licenceUrl: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
    sourceUrl:
      "https://www.trade-tariff.service.gov.uk/api/v2/exchange_rates/files/monthly_xml_2026-10.xml",
  },
  {
    id: "treasury",
    role: "official",
    nameEn: "U.S. Treasury reporting rates",
    nameAr: "أسعار الإبلاغ لوزارة الخزانة الأمريكية",
    summaryEn:
      "Quarterly corroborating series. Treasury Fiscal Data publishes these rates free of restriction for commercial and non-commercial use.",
    summaryAr:
      "سلسلة فصلية مساندة. تنشرها بيانات المالية العامة لوزارة الخزانة بلا قيد على الاستخدام التجاري وغير التجاري.",
    licence: "U.S. Treasury Fiscal Data — free, without restriction",
    licenceUrl: "https://fiscaldata.treasury.gov/api-documentation/",
    sourceUrl:
      "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange",
  },
  {
    id: "cbl-feed",
    role: "official",
    nameEn: "Optional CBL feed",
    nameAr: "تغذية اختيارية لمصرف ليبيا المركزي",
    summaryEn:
      "Disabled unless CBL_FEED_URL points at a JSON feed you are allowed to copy. The app does not scrape the Central Bank of Libya website.",
    summaryAr:
      "تبقى متوقفة ما لم يُضبط CBL_FEED_URL على تغذية JSON مسموح بنسخها. التطبيق لا يجمع بيانات موقع مصرف ليبيا المركزي.",
    licence: "Determined by the feed you configure",
    licenceUrl: "https://cbl.gov.ly/en/currency-exchange-rates/",
    sourceUrl: "https://cbl.gov.ly/en/currency-exchange-rates/",
  },
  {
    id: "manual",
    role: "manual",
    nameEn: "Manual entry",
    nameAr: "إدخال يدوي",
    summaryEn: "Rates typed by an operator. Use this for a CBL fixing you have read yourself, or for a parallel quote you are allowed to record.",
    summaryAr: "أسعار يكتبها المشغّل. استعملها لتثبيت قرأته بنفسك من مصرف ليبيا المركزي، أو لسعر موازٍ يحق لك تسجيله.",
    licence: "Operator supplied",
    licenceUrl: "https://cbl.gov.ly/en/currency-exchange-rates/",
    sourceUrl: "https://cbl.gov.ly/en/currency-exchange-rates/",
  },
  {
    id: "sample",
    role: "parallel",
    nameEn: "Synthetic parallel sample",
    nameAr: "عينة موازية تركيبية",
    summaryEn:
      "A labeled illustration. A fixed monthly premium is applied to the HMRC series. It is not a market quote and must not be used for settlement.",
    summaryAr:
      "رسم توضيحي معلّم. تُطبَّق علاوة شهرية ثابتة على سلسلة الهيئة البريطانية. ليست سعر سوق ولا تصلح للتسوية.",
    licence: "Synthetic — generated by this repository",
    licenceUrl: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
    sourceUrl: "src/lib/rates/sample.ts",
  },
];

export function catalogById(id: string): CatalogEntry | null {
  return PROVIDER_CATALOG.find((entry) => entry.id === id) ?? null;
}

export const OFFICIAL_PREFERENCE = ["manual", "cbl-feed", "hmrc", "treasury"] as const;
export const PARALLEL_PREFERENCE = ["manual", "sample"] as const;
